---
awx_url: "http://localhost:30080"
awx_username: "admin"
awx_password: "password"

awx_connection:
  controller_host: "http://localhost:30080"
  controller_username: "admin"
  controller_password: "password"

awx_cleanup:
  job_templates: ['Demo Job Template']
  credentials: [{name: 'Demo Credential', type: 'Machine'}]
  inventories: [{name: 'Demo Inventory', organization: 'Default'}]
  projects: ["Demo Project"]
  organizations: []

awx:
  organizations: [ { name: Default } ]
  credentials: [ { name: root, credential_type: Machine, organization: Default, inputs: { username: root, password: root } } ]
  projects: [ { name: ansible, organization: Default, scm_type: git, scm_url: https://github.com/valengus/awx.git } ]
  inventories: [ { name: local, organization: Default } ]
  inventory_sources: [ { name: "local-scm-inv", inventory: local, overwrite: true, update_on_launch: true, organization: Default, source: scm, source_project: ansible, source_path: projects/local/inventories/hosts.ini }]
  job_templates: [ { name: awx-setup, job_type: run, organization: Default, inventory: local, project: ansible, playbook: environments/local/playfile/awx-setup.yml, credentials: [root] } ]

awx_organizations:
- name: Default
  credentials:
  - { name: root, credential_type: Machine, inputs: { username: root, password: root } }
  projects:
  - name: ansible
    organization: Default
    scm_type: git
    scm_url: https://github.com/valengus/awx.git
    inventories:
    - name: local
      inventory_sources:
      - { name: "local-scm-inv", inventory: local, overwrite: true, update_on_launch: true, organization: Default, source: scm, source_project: ansible, source_path: projects/local/inventories/hosts.ini }
      job_templates:
      - { name: awx-setup, job_type: run, organization: Default, inventory: local, project: ansible, playbook: environments/local/playfile/awx-setup.yml, credentials: [root] }
