---
awx_url: "http://localhost:30080"
awx_username: "admin"
awx_password: "password"

awx_connection:
  controller_host: "{{ awx_url }}"
  controller_username: "{{ awx_username }}"
  controller_password: "{{ awx_password }}"

awx_cleanup:
  job_templates: ['Demo Job Template']
  credentials: [{name: 'Demo Credential', type: 'Machine'}]
  inventories: [{name: 'Demo Inventory', organization: 'Default'}]
  projects: ["Demo Project"]
  organizations: []

awx:
  organizations: 
  - name: Default
  credentials:
  - { name: 'root:root', organization: Default, credential_type: Machine,  inputs: { username: root, password: root } }
  projects: 
  - { name: valengus-awx, organization: Default, scm_type: git, scm_url: https://github.com/valengus/awx.git }
  inventories:
  - { name: local, organization: Default }
  inventory_sources:
  - { name: "local-scm-inv", inventory: local, overwrite: true, update_on_launch: true, organization: Default, source: scm, source_project: valengus-awx, source_path: environments/local/inventories/hosts.ini }
  job_templates:
  - name: awx-setup
    job_type: run
    playbook: environments/local/playfile/awx-setup.yml
    organization: Default
    inventory: local
    project: valengus-awx
    credentials:
    - 'root:root'
